version: '3'

services:
    python:
        image: python:3.9
        container_name: lido
        volumes:
            - ./:/lido
        ports:
            - 13013:8000
        command: bash -c "cd ./lido && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000">

networks:
  default:
    external:
      name: charkoal